---
- hosts: all
  gather_facts: yes
  tasks:
  - name: Assert that local prerequisites are met
    import_tasks: ./check_local_prerequisites.yml
    when: "'localhost' in group_names"
    tags:
    - check_prerequisites

  - name: Install required packages
    become: yes
    when: "'localhost' not in group_names"
    tags:
    - always
    apt:
      name: 
      - curl
      state: present
  
  - name: Root CA
    import_tasks: ./root_ca.yml
    when: "'localhost' in group_names"
    tags:
    - generate_the_root_ca
  
  - name: Etcd
    import_tasks: ./etcd.yml

  - name: Setup the Kubernetes Control Plane
    import_tasks: ./control_plane.yml

  - name: Setup the Kubernetes Workers
    import_tasks: ./workers.yml
