#!/usr/bin/env bash
K8S_COMPONENT=$1
K8S_RELEASE_VERSION=$2
HYPERKUBE_BINARY="/usr/bin/hyperkube_$K8S_RELEASE_VERSION"

function wrap_hyperkube () {
    local kube_component=$1
    local component_version=$2
    local component_runner="/usr/bin/${kube_component}_${component_version}"
    sudo bash -c "echo \"#!/usr/bin/env bash\" > $component_runner"
    sudo bash -c "echo \"$HYPERKUBE_BINARY $kube_component \\\$@\" >> $component_runner"
    sudo chmod +x "$component_runner"
    sudo ln -s $component_runner "/usr/bin/$kube_component"
}

pushd /tmp

container_id=$(docker create gcr.io/google-containers/hyperkube:$K8S_RELEASE_VERSION)

sudo docker cp $container_id:/hyperkube "$HYPERKUBE_BINARY"
sudo chmod u+x "$HYPERKUBE_BINARY"

docker rm -f $container_id

wrap_hyperkube "$K8S_COMPONENT" "$K8S_RELEASE_VERSION" 

popd


