
kubernetes_version: v1.15.0
etcd3_version: v3.3.13
etcd_data_encryption_key: s3cr3t
kubernetes_cluster_id: kubernetes-the-hard-way
kubernetes_cluster_name: Kubernetes The Hard Way

# DO NOT CHANGE THINGS BELOW
kubernetes_workers: "{{ groups['workers'] | sort }}"
kubernetes_masters: "{{ groups['masters'] | sort }}"
etcd_peers: "{{ groups['etcd_peers'] | sort }}"
kubernetes_api_ip_address: "{{ kubernetes_masters | map('extract', hostvars, ['ansible_eth1', 'ipv4', 'address']) | list | first }}"
etcd_cluster_ip_address: "{{ etcd_peers | map('extract', hostvars, ['ansible_eth1', 'ipv4', 'address']) | list | first }}"
pki_dir: "{{ playbook_dir }}/pki"
root_ca_dir: "{{ pki_dir }}/root-ca"
root_ca_cert_file: "{{root_ca_dir}}/ca.pem"
root_ca_key_file: "{{root_ca_dir}}/ca-key.pem"