
kubernetes_version: v1.15.0
etcd3_version: v3.3.13
kubernetes_cluster_id: kubernetes-the-hard-way
kubernetes_cluster_name: Kubernetes The Hard Way

# DO NOT CHANGE THINGS BELOW
kubernetes_workers: "{{ groups['workers'] }}"
kubernetes_masters: "{{ groups['masters'] }}"
kubernetes_api_ip_address: "{{ kubernetes_masters |  map('extract', hostvars, 'ansible_eth1') | list | map(attribute='ipv4') | list | map(attribute='address') | list | first }}"
pki_dir: "{{ playbook_dir }}/pki"
root_ca_dir: "{{ pki_dir }}/root-ca"
root_ca_cert_file: "{{root_ca_dir}}/ca.pem"
root_ca_key_file: "{{root_ca_dir}}/ca-key.pem"